/// <reference types="vite/client" />

declare const __SIDECAR_MSG__: {
  REQUEST_PROBLEM_TITLE: 'REQUEST_PROBLEM_TITLE';
  PROBLEM_TITLE_UPDATE: 'PROBLEM_TITLE_UPDATE';
  GET_PROBLEM_DATA: 'GET_PROBLEM_DATA';
  PROBLEM_DATA_RESPONSE: 'PROBLEM_DATA_RESPONSE';
  INJECT_CODE: 'INJECT_CODE';
  INJECTION_RESULT: 'INJECTION_RESULT';
  HIGHLIGHT_LINES: 'HIGHLIGHT_LINES';
  SHOW_SUGGESTION: 'SHOW_SUGGESTION';
  RESOLVE_SUGGESTION: 'RESOLVE_SUGGESTION';
  CLOSE_PANEL: 'CLOSE_PANEL';
  SUGGESTION_RESOLVED: 'SUGGESTION_RESOLVED';
  SELECTION_CHANGED: 'SELECTION_CHANGED';
  INJECT_CODE_FROM_CONTENT_SCRIPT: 'INJECT_CODE_FROM_CONTENT_SCRIPT';
  GET_EDITOR_CONTENT_FROM_CONTENT_SCRIPT: 'GET_EDITOR_CONTENT_FROM_CONTENT_SCRIPT';
  SETUP_SELECTION_LISTENER_FROM_CONTENT_SCRIPT: 'SETUP_SELECTION_LISTENER_FROM_CONTENT_SCRIPT';
  GET_EDITOR_SELECTION_FROM_CONTENT_SCRIPT: 'GET_EDITOR_SELECTION_FROM_CONTENT_SCRIPT';
  SHOW_SUGGESTION_FROM_CONTENT_SCRIPT: 'SHOW_SUGGESTION_FROM_CONTENT_SCRIPT';
  RESOLVE_SUGGESTION_FROM_CONTENT_SCRIPT: 'RESOLVE_SUGGESTION_FROM_CONTENT_SCRIPT';
  HIGHLIGHT_LINES_FROM_CONTENT_SCRIPT: 'HIGHLIGHT_LINES_FROM_CONTENT_SCRIPT';
  SUGGESTION_RESOLVED_FROM_PAGE: 'SUGGESTION_RESOLVED_FROM_PAGE';
  MONACO_SELECTION_CHANGED: 'MONACO_SELECTION_CHANGED';
};
